// image-to-grid — turn a source render into a QBSK glyph asset (docs/engine.md §11.17).
//
//   node bench/image-to-grid.mjs --png art.png --cols 120 --rows 40 \
//        --normalise --gamma 0.6 --out examples/res/scene.qbdata --name CELL
//
// Flags:
//   --png <path>       the SOURCE render. Not ASCII art: converting a picture OF
//                      glyphs samples across glyph boundaries and loses the structure
//                      twice, measured during an earlier release spike.
//   --cols / --rows    the grid. A 1:2 cell means a 3:2 image maps without distortion.
//   --normalise        stretch the image's own range across the ramp
//   --gamma <n>        bend the curve; below 1 lifts shadows
//   --edges <n>        gradient magnitude above which a cell becomes an edge glyph
//   --aspect <n>       cell height over width, for those edge glyphs (default 2.0)
//   --name <IDENT>     the entry name inside the .qbdata (default ART)
//   --out <path>       where to write (omit to print the grid and the score only)
//
// THIS SCRIPT WRITES FILES, so it is not part of `npm run bench` — a gate with side
// effects is not a gate, and rewriting an asset turns its golden red.

import { readFileSync, writeFileSync } from "node:fs";
import { decodePng } from "../dist/tools/pngDecode.js";
import { convertImage, fidelity } from "../dist/tools/imageToGrid.js";

const NL = "\n";

function arg(name, fallback = null) {
  const i = process.argv.indexOf(`--${name}`);
  return i === -1 || i + 1 >= process.argv.length ? fallback : process.argv[i + 1];
}
const has = (n) => process.argv.includes(`--${n}`);

/** The measured coverage from E4, so the score is against a real font. */
function measuredCoverage() {
  const data = readFileSync(new URL("../examples/res/ramp.qbdata", import.meta.url), "utf8");
  const body = data.slice(data.indexOf('"coverage"'));
  const cov = new Map();
  for (const m of body.matchAll(/"(.)": *([0-9.]+)/g)) {
    cov.set(m[1], Number(m[2]));
  }
  return cov;
}

const png = arg("png");
const cols = Number(arg("cols", "120"));
const rows = Number(arg("rows", "40"));
if (png === null) {
  console.error("usage: node bench/image-to-grid.mjs --png <file> [--cols N --rows N] [--out f]");
  process.exit(2);
}

const decoded = decodePng(readFileSync(png));
const grid = convertImage(
  {
    pixels: decoded.pixels,
    width: decoded.width,
    height: decoded.height,
    channels: decoded.channels,
  },
  {
    cols,
    rows,
    normalise: has("normalise"),
    gamma: Number(arg("gamma", "1")),
    edgeThreshold: arg("edges") === null ? null : Number(arg("edges")),
    cellAspect: Number(arg("aspect", "2")),
  },
);

const flat = grid.lines.join("");
const blank = [...flat].filter((c) => c === " ").length / flat.length;
const score = fidelity(grid, measuredCoverage());

console.log(`source: ${png} — ${decoded.width}x${decoded.height}, ${decoded.channels} channels`);
console.log(`grid  : ${cols}x${rows} = ${cols * rows} cells`);
console.log(`glyphs: ${new Set(flat).size} distinct, ${(blank * 100).toFixed(1)}% blank`);
console.log(`order preserved: ${(score * 100).toFixed(2)}%`);
if (score < 0.8) {
  console.log("");
  console.log("  ⚠ Below 0.80. The grid is not carrying the source's ordering of light.");
  console.log("    Usually the tone curve: try --normalise --gamma 0.6 before blaming the ramp.");
}

const out = arg("out");
if (out === null) {
  console.log("");
  console.log(grid.lines.join(NL));
  console.log("");
  console.log("(no --out given; nothing written)");
} else {
  const name = arg("name", "ART");
  const asset = out.split(/[\\/]/).pop();
  const header = [
    "// GENERATED by bench/image-to-grid.mjs, do not hand-edit.",
    `// source: ${png}`,
    `// grid: ${cols}x${rows}, order preserved ${(score * 100).toFixed(2)}%`,
    "//",
    "// A converted render, ready to draw (docs/engine.md §11.17):",
    "//",
    `//     use "res/${asset}" as art`,
    `//     put art.${name}["lines"] at (0, 0)`,
    "//",
    "// Only the glyphs are written. The per-cell intensity and colour the conversion",
    "// also produced stay in the API: the converter is deterministic and the source",
    "// render is kept, so a scene that later wants a flickering torch reconverts",
    "// rather than carrying 12,000 floats it does not use yet.",
    "",
    "shape art_grid",
    "    cols: int",
    "    rows: int",
    "    lines: list",
    "",
    `${name} = {"cols": ${cols}, "rows": ${rows}, "lines": [${grid.lines.map((l) => JSON.stringify(l)).join(", ")}]}`,
    "",
  ].join(NL);
  writeFileSync(out, header, "utf8");
  console.log("");
  console.log(`wrote ${out}`);
}
