// measure-ramp — turn a rendered glyph strip into a density ramp (docs/engine.md §11.15).
//
// The engine's default ramp is hand-written, and "does % cover more ink than #?" is a
// question about a font, not an opinion. This measures the answer.
//
//   node bench/measure-ramp.mjs --selftest
//   node bench/measure-ramp.mjs --png strip.png --glyphs " .:-=+*#%@" --out examples/res/ramp.qbdata
//
// Flags:
//   --png <path>        the strip: one glyph per equal-width cell, left to right
//   --glyphs "<chars>"  what the strip renders, in order
//   --out <path>        where to write the .qbdata (omit to print only)
//   --light-on-dark     the strip is light ink on a dark background
//   --markers           the strip is framed by a full block █ at each end; find them
//                       and measure between, so a ROUGH crop works and a shell that
//                       echoes surrounding quotes does not shift the cells
//   --rows y0:y1        measure only this band of rows — one line of a screenshot
//   --selftest          measure a synthetic strip of known coverage instead
//
// THIS SCRIPT WRITES FILES, so it is not part of `npm run bench` — a gate with side
// effects is not a gate, and rewriting a .qbdata turns the determinism tests red.
//
// The brief's own warning, kept: if the measured order comes out identical to the
// hand-written guess, suspect the measurement. Both are printed and diffed below for
// exactly that reason.

import { readFileSync, writeFileSync } from "node:fs";
import { decodePng } from "../dist/tools/pngDecode.js";
import { cropColumns, cropRows, markerBounds, measureCoverage, normalise } from "../dist/tools/rampMeasure.js";
import { DENSITY_RAMP, rampFromTable } from "../dist/engine/ramp.js";

function arg(name, fallback = null) {
  const i = process.argv.indexOf(`--${name}`);
  return i === -1 || i + 1 >= process.argv.length ? fallback : process.argv[i + 1];
}
const has = (name) => process.argv.includes(`--${name}`);

/** A strip whose coverage arithmetic already knows: 0, 1/4, 1/2, 3/4, 1. */
function syntheticStrip() {
  const fills = [0, 0.25, 0.5, 0.75, 1];
  const glyphs = " .-+#";
  const cell = 8, height = 8, width = fills.length * cell;
  const pixels = new Uint8Array(width * height * 3).fill(255);
  fills.forEach((fill, i) => {
    for (let y = 0; y < Math.round(fill * height); y += 1) {
      for (let x = i * cell; x < (i + 1) * cell; x += 1) {
        const at = (y * width + x) * 3;
        pixels[at] = 0; pixels[at + 1] = 0; pixels[at + 2] = 0;
      }
    }
  });
  return { pixels, width, height, channels: 3, glyphs, expected: fills };
}

function report(measured, normalised, ramp) {
  console.log("\nmeasured coverage, as read:\n");
  console.log("  glyph   raw      normalised");
  console.log("  -----   ------   ----------");
  for (let i = 0; i < measured.length; i += 1) {
    const g = measured[i].glyph === " " ? "' '" : ` ${measured[i].glyph} `;
    console.log(
      `   ${g}    ${measured[i].coverage.toFixed(4)}   ${normalised[i].coverage.toFixed(4)}`,
    );
  }
  console.log(`\n  measured ramp : ${JSON.stringify(ramp)}`);
  console.log(`  hardcoded ramp: ${JSON.stringify(DENSITY_RAMP)}`);
  if (ramp === DENSITY_RAMP) {
    console.log(
      "\n  ⚠ The measured order is IDENTICAL to the hand-written guess.\n" +
      "    Suspect the measurement before celebrating it: check the strip really\n" +
      "    renders the glyphs it names, in that order, one per cell.",
    );
  } else {
    console.log("\n  the two orders differ — which is what a measurement is for.");
  }
}

function qbdata(glyphs, entries, source) {
  const rows = entries
    .map((e) => `${JSON.stringify(e.glyph)}: ${e.coverage.toFixed(6)}`)
    .join(", ");
  return `// GENERATED by bench/measure-ramp.mjs, do not hand-edit.
// source: ${source}
//
// Ink coverage per glyph, measured rather than guessed (docs/engine.md §11.15).
// \`glyphs\` is the ramp itself, sparse to dense — pass it straight to glyph():
//
//     use "res/ramp.qbdata" as ramp
//     put glyph(intensity, ramp.MEASURED["glyphs"]) at (x, y)
//
// \`coverage\` keeps the number behind each glyph, so a later measurement can be
// diffed against this one instead of merely replacing it.

shape ramp_table
    glyphs: str
    coverage: dict

MEASURED = {"glyphs": ${JSON.stringify(glyphs)}, "coverage": {${rows}}}
`;
}

function main() {
  if (has("selftest")) {
    const s = syntheticStrip();
    const measured = measureCoverage({ ...s, inkIsDark: true });
    const normalised = normalise(measured);
    const ramp = rampFromTable(normalised);
    report(measured, normalised, ramp);

    let bad = 0;
    measured.forEach((m, i) => {
      if (Math.abs(m.coverage - s.expected[i]) > 1e-9) {
        console.error(
          `  MISMATCH ${JSON.stringify(m.glyph)}: measured ${m.coverage}, expected ${s.expected[i]}`,
        );
        bad += 1;
      }
    });
    if (ramp !== s.glyphs) {
      console.error(`  MISMATCH ramp: got ${JSON.stringify(ramp)}, expected ${JSON.stringify(s.glyphs)}`);
      bad += 1;
    }
    console.log(
      bad === 0
        ? "\nselftest OK — the pipeline reports the coverage the strip was built with."
        : `\nselftest FAILED — ${bad} mismatch(es).`,
    );
    process.exit(bad === 0 ? 0 : 1);
  }

  const png = arg("png");
  const glyphs = arg("glyphs");
  if (png === null || glyphs === null) {
    console.error("usage: node bench/measure-ramp.mjs --png <strip.png> --glyphs \"<chars>\" [--out <file>]");
    console.error("       node bench/measure-ramp.mjs --selftest");
    process.exit(2);
  }

  const decoded = decodePng(readFileSync(png));
  const inkIsDark = !has("light-on-dark");
  let strip = {
    pixels: decoded.pixels,
    width: decoded.width,
    height: decoded.height,
    channels: decoded.channels,
  };
  let glyphList = glyphs;

  const rows = arg("rows");
  if (rows !== null) {
    const [y0, y1] = rows.split(":").map(Number);
    strip = cropRows(strip, y0, y1);
    console.log(`--rows: measuring y ${y0}..${y1} (${strip.height}px tall)`);
  }

  if (has("markers")) {
    // A full block fills its cell, so its columns are the only ones inked the whole
    // height. Anything outside the frame — a shell echoing its own quotes, say — is
    // ignored, which plain ink bounds could not do.
    const bounds = markerBounds({ ...strip, inkIsDark });
    if (bounds === null) {
      console.error("--markers: could not find two full-block markers; is the strip framed by █?");
      process.exit(1);
    }
    strip = cropColumns(strip, bounds.x0, bounds.x1);
    const cells = [...glyphList].length;
    console.log(
      `--markers: measuring between the blocks, x ${bounds.x0}..${bounds.x1} ` +
      `(${strip.width}px for ${cells} glyphs = ${(strip.width / cells).toFixed(2)}px/cell)`,
    );
  }

  const measured = measureCoverage({ ...strip, glyphs: glyphList, inkIsDark });
  const normalised = normalise(measured);
  const ramp = rampFromTable(normalised);
  console.log(`strip: ${png} — ${decoded.width}x${decoded.height}, ${decoded.channels} channels`);
  report(measured, normalised, ramp);

  const out = arg("out");
  if (out !== null) {
    const sorted = [...normalised].sort((a, b) => a.coverage - b.coverage);
    writeFileSync(out, qbdata(ramp, sorted, png), "utf8");
    console.log(`\nwrote ${out}`);
  } else {
    console.log("\n(no --out given; nothing written)");
  }
}

main();
