// an earlier release — slices a reference sprite sheet (PNG) into individual sprites.
//
// Pipeline, each stage owned by whichever side can actually do it
// (06-active-language-phases.md's an earlier release entry has the full reasoning):
//   1. PNG bytes -> RGB(A) pixels: host-side (src/tools/pngDecode.ts) — DEFLATE is a
//      bit-level format, QBSK has no bitwise operators.
//   2. RGB(A) pixels -> a small palette + palette-indexed pixels: host-side — this is
//      mechanical format conversion (deduplicating colors), not creative content.
//   3. Cropping the indexed sheet into per-cell pixel arrays: QBSK
//      (examples/lib/spritesheet.qbsk) — pure index arithmetic, genuinely QBSK's own.
//   4. Writing each cell as a `.qbdata` + SVG: host-side (file I/O — QBSK has no
//      file-write native, checked in src/interp/natives.ts).
//
// Run: node bench/spritesheet-slice.mjs <input.png> <cellWidth> <cellHeight> <outDir> [namePrefix]
// Output: <outDir>/<namePrefix>_r<row>_c<col>.qbdata and matching .svg, one pair per
// non-empty cell (a fully-transparent cell is skipped, not written as a blank sprite).

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { decodePng } from "../dist/tools/pngDecode.js";
import { runQbsk } from "../dist/interp/interpreter.js";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");

const [, , inputArg, cellWidthArg, cellHeightArg, outDirArg, namePrefixArg] = process.argv;
if (!inputArg || !cellWidthArg || !cellHeightArg || !outDirArg) {
  console.error(
    "usage: node bench/spritesheet-slice.mjs <input.png> <cellWidth> <cellHeight> <outDir> [namePrefix]",
  );
  process.exit(1);
}
const cellWidth = Number(cellWidthArg);
const cellHeight = Number(cellHeightArg);
const outDir = resolve(root, outDirArg);
const namePrefix = namePrefixArg ?? "sprite";

const png = decodePng(readFileSync(resolve(root, inputArg)));
console.log(`decoded ${inputArg}: ${png.width}x${png.height}, ${png.channels} channels`);

// Quantize to a small palette: index 0 is reserved for "empty" (pixelart.qbsk's own
// convention) and covers both fully-transparent RGBA pixels and (for RGB input, which
// has no alpha channel at all) pure-black pixels are NOT treated as empty — RGB has no
// transparency concept, so every RGB pixel is a real color.
const palette = [];
const colorToIndex = new Map();
const pixelIndices = new Int32Array(png.width * png.height);
for (let i = 0; i < png.width * png.height; i += 1) {
  const o = i * png.channels;
  const r = png.pixels[o];
  const g = png.pixels[o + 1];
  const b = png.pixels[o + 2];
  const a = png.channels === 4 ? png.pixels[o + 3] : 255;
  if (a === 0) {
    pixelIndices[i] = 0;
    continue;
  }
  const key = `${r},${g},${b}`;
  let index = colorToIndex.get(key);
  if (index === undefined) {
    palette.push(`#${[r, g, b].map((v) => v.toString(16).padStart(2, "0")).join("")}`);
    index = palette.length; // 1-based: pixel value k means palette[k-1]
    colorToIndex.set(key, index);
  }
  pixelIndices[i] = index;
}
console.log(`quantized to a ${palette.length}-color palette`);

const cols = Math.floor(png.width / cellWidth);
const rows = Math.floor(png.height / cellHeight);
console.log(`slicing into a ${cols}x${rows} grid of ${cellWidth}x${cellHeight} cells`);

const qbskSource = `
use "spritesheet.qbsk" as sheet
var pixels = ${JSON.stringify(Array.from(pixelIndices))}
var size = sheet.gridSize(${png.width}, ${png.height}, ${cellWidth}, ${cellHeight})
var row = 0
while row < size["rows"]
    var col = 0
    while col < size["cols"]
        var cell = sheet.cropCell(${png.width}, ${png.height}, pixels, ${cellWidth}, ${cellHeight}, col, row)
        print(sheet.cellIsEmpty(cell))
        print(cell)
        col += 1
    row += 1
`;
const result = runQbsk(qbskSource, "examples/lib/_slice_driver.qbsk", undefined, {
  baseDir: resolve(root, "examples/lib"),
});
if (result.error) {
  console.error("slicing failed:", result.error.message);
  process.exit(1);
}

mkdirSync(outDir, { recursive: true });
let written = 0;
let skipped = 0;
let lineIndex = 0;
for (let row = 0; row < rows; row += 1) {
  for (let col = 0; col < cols; col += 1) {
    const isEmpty = result.out[lineIndex] === "true";
    const cellPixels = JSON.parse(result.out[lineIndex + 1]);
    lineIndex += 2;
    if (isEmpty) {
      skipped += 1;
      continue;
    }
    const name = `${namePrefix}_r${row}_c${col}`;
    const entryName = name.toUpperCase();

    const qbdataList = (values, quote) => `[${values.map((v) => (quote ? `"${v}"` : v)).join(", ")}]`;
    const qbdataText = [
      `// GENERATED by bench/spritesheet-slice.mjs from ${inputArg}, do not hand-edit.`,
      `// External reference material (an earlier release) — NOT QBSK-generated content, kept`,
      "// under examples/res/assets/reference/ specifically so it never mixes with",
      "// examples/lib/pixelart.qbsk's own from-scratch output.",
      "//",
      "// pixel value 0 means empty; pixel value k (1..len(palette)) means palette[k-1].",
      "",
      "shape pixel_sprite",
      "    width: int",
      "    height: int",
      "    palette: list",
      "    pixels: list",
      "",
      `${entryName} = {"width": ${cellWidth}, "height": ${cellHeight}, "palette": ${qbdataList(palette, true)}, "pixels": ${qbdataList(cellPixels, false)}}`,
      "",
    ].join("\n");
    writeFileSync(resolve(outDir, `${name}.qbdata`), qbdataText, "utf8");

    const rects = [];
    for (let y = 0; y < cellHeight; y += 1) {
      for (let x = 0; x < cellWidth; x += 1) {
        const v = cellPixels[y * cellWidth + x];
        if (v === 0) continue;
        rects.push(`  <rect x="${x}" y="${y}" width="1" height="1" fill="${palette[v - 1]}"/>`);
      }
    }
    const svgText = [
      `<svg xmlns="http://www.w3.org/2000/svg" width="${cellWidth}" height="${cellHeight}" viewBox="0 0 ${cellWidth} ${cellHeight}" shape-rendering="crispEdges">`,
      ...rects,
      "</svg>",
      "",
    ].join("\n");
    writeFileSync(resolve(outDir, `${name}.svg`), svgText, "utf8");
    written += 1;
  }
}
console.log(`wrote ${written} sprites to ${outDir} (${skipped} empty cells skipped)`);
