// An earlier release — the procedural-RPG test scene (the design notes).
//
// Host-side world generator: rolls NPC personalities (DF-style facets/values,
// the design notes §3) from the ONE seeded PRNG this project has
// (src/util/random.ts), and writes them out as a `.qbdata` file the scene loads.
//
// WHY HOST-SIDE, NOT A NEW QBSK NATIVE: QBSK has no bitwise operators (checked: the
// lexer has no XOR/shift tokens), and mulberry32 needs them (Math.imul, `^`, `>>>`). A
// real seeded generator genuinely cannot be written as a QBSK-language library today —
// this is exactly the kind of gap an earlier release criterion 1 asks to be named, not silently
// routed around. It's recorded as a finding in an earlier release decision, not solved here:
// this script sidesteps it by generating data once, host-side, the same way DF's own
// world generation is a distinct pass before play starts, not a per-frame system.
//
// Run: node bench/worldgen-gen.mjs [seed]
// Same seed -> byte-identical output, every time (this is the determinism proof for
// An earlier release criterion 4 — re-run this and diff the output).

import { mulberry32, streamSeed } from "../dist/util/random.js";
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const seed = Number(process.argv[2] ?? 27); // default seed: 27

// Four independent sub-streams, DF's own pattern (the design notes §5) — regenerating
// NPCs must never change locations or professions, and vice versa.
const STREAM = { npc: 0, location: 1, profession: 2, history: 3 };

const npcRng = mulberry32(streamSeed(seed, STREAM.npc));
// An earlier release: this stream was declared in that release but never actually drawn from —
// profession was round-robin, not rolled. Now it is: one float per NPC, consumed by
// lib/population.qbsk's weightedPick() inside the scene itself, not here — the
// selection ALGORITHM is QBSK code (testable, composable); only the raw entropy is
// host-side, the same split every other host/QBSK boundary in this project draws.
const professionRng = mulberry32(streamSeed(seed, STREAM.profession));

const FACETS = ["ambition", "cruelty", "bashfulness", "sociability"];
const VALUES = ["tradition", "cooperation", "honesty"];
const LOCATIONS = ["ashford", "millbrook", "cairn_hollow"];
const NPC_COUNT = 8;

// DF weights toward the middle so extremes are rare and notable (the design notes §3);
// averaging two rolls approximates that without needing a real distribution function.
function weightedRoll(rng, min, max) {
  const a = rng();
  const b = rng();
  return Math.round((min + (a + b) * 0.5 * (max - min)) * 10) / 10;
}

const npcs = [];
for (let i = 0; i < NPC_COUNT; i += 1) {
  const facets = {};
  for (const f of FACETS) facets[f] = weightedRoll(npcRng, 0, 100);
  const values = {};
  for (const v of VALUES) values[v] = weightedRoll(npcRng, -50, 50);
  npcs.push({
    id: `npc_${i}`,
    location: LOCATIONS[i % LOCATIONS.length],
    profession_roll: Math.round(professionRng() * 1000) / 1000,
    facets,
    values,
  });
}

function qbdataDict(obj, indent = "") {
  const parts = Object.entries(obj).map(([k, v]) => {
    if (typeof v === "object" && v !== null) {
      return `"${k}": {${Object.entries(v)
        .map(([k2, v2]) => `"${k2}": ${v2}`)
        .join(", ")}}`;
    }
    if (typeof v === "string") return `"${k}": "${v}"`;
    return `"${k}": ${v}`;
  });
  return `{${parts.join(", ")}}`;
}

const lines = [
  "// worldgen_npcs.qbdata — GENERATED by bench/worldgen-gen.mjs, do not hand-edit.",
  `// seed=${seed} stream=npc(${STREAM.npc}) — regenerate: node bench/worldgen-gen.mjs ${seed}`,
  "//",
  "// Facets (0-100, how the NPC acts) and values (-50..50, what it believes) follow the",
  "// Dwarf Fortress model (14-dwarf-fortress-worldgen-research.md §3). Names are",
  "// placeholders — the phoneme name-generator is explicitly out of scope here.",
  "// profession_roll is a raw [0,1) float, not a profession string — the",
  "// scene resolves it against res/worldgen_professions.qbdata's PROFESSION_TABLE via",
  "// lib/population.qbsk's weightedPick() at load time, not here.",
  "",
  "shape npc",
  "    id: str",
  "    location: str",
  "    profession_roll: float",
  "    facets: dict",
  "    values: dict",
  "",
  ...npcs.map((n, i) => `NPC_${i} = ${qbdataDict(n)}`),
  "",
];

const outPath = resolve(root, "examples/res/worldgen_npcs.qbdata");
writeFileSync(outPath, lines.join("\n"), "utf8");
console.log(`wrote ${outPath} (seed=${seed}, ${npcs.length} NPCs)`);
